
export const universities = [
  "Arizona State University",
  "Auburn University",
  "Boston College",
  "Boston University",
  "Brigham Young University",
  "Brown University",
  "Carnegie Mellon University",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Duke University",
  "Emory University",
  "Florida International University",
  "Florida State University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Harvard University",
  "Indiana University",
  "Johns Hopkins University",
  "Louisiana State University",
  "Massachusetts Institute of Technology",
  "Miami University",
  "Michigan State University",
  "New York University",
  "North Carolina State University",
  "Northeastern University",
  "Northwestern University",
  "Ohio State University",
  "Penn State University",
  "Princeton University",
  "Purdue University",
  "Rice University",
  "Rutgers University",
  "Stanford University",
  "Stony Brook University",
  "Syracuse University",
  "Temple University",
  "Texas A&M University",
  "Tulane University",
  "UCLA",
  "UC Berkeley",
  "UC Davis",
  "UC San Diego",
  "UC Santa Barbara",
  "University of Alabama",
  "University of Arizona",
  "University of Central Florida",
  "University of Chicago",
  "University of Colorado Boulder",
  "University of Connecticut",
  "University of Florida",
  "University of Georgia",
  "University of Illinois Urbana-Champaign",
  "University of Iowa",
  "University of Kansas",
  "University of Kentucky",
  "University of Maryland",
  "University of Massachusetts Amherst",
  "University of Miami",
  "University of Michigan",
  "University of Minnesota",
  "University of Mississippi",
  "University of Missouri",
  "University of Nebraska",
  "University of North Carolina",
  "University of Notre Dame",
  "University of Oregon",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of South Carolina",
  "University of South Florida",
  "University of Southern California",
  "University of Tennessee",
  "University of Texas at Austin",
  "University of Utah",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Vanderbilt University",
  "Virginia Tech",
  "Wake Forest University",
  "Washington University in St. Louis",
  "Yale University",
]